import StoreProvider from "@/store/StoreProvider";
import "@/styles/globals.scss";
import DefaultLayout from "@/components/layouts/DefaultLayout";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <StoreProvider>

      <DefaultLayout>
        {children}
      </DefaultLayout>

    </StoreProvider>
  );
}
